default:
  base_config:
    scene: RaySquare

    build_path:
      win32: C:\Users\Fisher\Nextcloud\Documents\Unity\win-RL-Envs\UnityEnvironment.exe
      linux: /data/linux-RL-Envs/RL-Envs.x86_64

    reset_on_iteration: false
    n_agents: 10

  reset_config:
    force_reset: true

  sac_config:
    burn_in_step: 10
    n_step: 5
    use_rnn: true

wall:
  base_config: &wall_base
    name: "ray5_wall_nopre_{time}"
    max_iter: 200
  reset_config: &wall_reset
    avoid_wall: false
    ray_length: 5

wall_pre:
  base_config:
    <<: *wall_base
    name: "ray5_wall_pre_{time}"
  reset_config: *wall_reset
  sac_config:
    use_prediction: true

nowall:
  base_config: &nowall_base
    name: "ray5_nowall_nopre_{time}"
    max_iter: 200
  reset_config: &nowall_reset
    avoid_wall: true
    ray_length: 5

nowall_pre:
  base_config:
    <<: *nowall_base
    name: "ray5_nowall_pre_{time}"
  reset_config: *nowall_reset
  sac_config:
    use_prediction: true
