default:
  base_config:
    build_path:
      win32: C:\Users\Fisher\Nextcloud\Documents\Unity\win-RL-Envs\UnityEnvironment.exe
      linux: /data/linux-RL-Envs/RL-Envs.x86_64

    scene: track
    max_iter: -1
    n_agents: 10

  sac_config:
    seed: 42
    n_step: 3