base_config:
  build_path: 
    win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
    linux: /data/linux-RL-Envs/RL-Envs.x86_64
  scene: ContinousSimpleRoller

  save_model_per_iter: 50
  reset_on_iteration: false

reset_config:
  force_reset: true

replay_config:
  beta: 0.1
  beta_increment_per_sampling: 0

sac_config:
  seed: 42

  n_step: 10

  tau: 0.9
  _lambda: 0.99
  init_log_alpha: -4.6