default:
  base_config:
    env_name: UGVRace
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    n_envs: 50
    max_step: 300000

  nn_config:
    rep:
      blur: 0
      brightness: 1
      ray_random: 0

  sac_config:
    write_summary_per_step: 1000 # Write summaries in TensorBoard every N steps
    save_model_per_step: 5000 # Save model every N steps

    n_step: 3

    v_lambda: 1

    use_rnd: true
    rnd_n_sample: 50

atc:
  base_config:
    name: "atc_{time}"
  sac_config:
    siamese: ATC

byol:
  base_config:
    name: "byol_{time}"
  sac_config:
    siamese: BYOL

atc_q:
  base_config:
    name: "atc_q_{time}"
  sac_config:
    siamese: ATC
    siamese_use_q: true

byol_q:
  base_config:
    name: "byol_q_{time}"
  sac_config:
    siamese: BYOL
    siamese_use_q: true

atc_q_ada:
  base_config:
    name: "atc_q_ada_{time}"
  sac_config:
    siamese: ATC
    siamese_use_q: true
    siamese_use_adaptive: true

byol_q_ada:
  base_config:
    name: "byol_q_ada_{time}"
  sac_config:
    siamese: BYOL
    siamese_use_q: true
    siamese_use_adaptive: true
