default:
  base_config:
    env_name: UGV
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    n_agents: 50
    max_step: 300000
    reset_on_iteration: false

  reset_config:
    force_reset: true
    bounding_box_random: 0
    semantic_segmentation_random: 0
    success_reward: 3
    failure_reward: -1
    failure_backward_reward: -4

  nn_config:
    rep:
      blur: 0
      brightness: 1
      ray_random: 0
      need_speed: true

  sac_config:
    write_summary_per_step: 1000 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 30
    seq_encoder: RNN

    v_lambda: 1

    use_rnd: true
    rnd_n_sample: 50

  oc_config:
    nn_config:
      rep:
        blur: 0
        brightness: 1
        ray_random: 0
        need_speed: true

atc:
  base_config:
    name: "atc_{time}"
  sac_config:
    siamese: ATC

byol:
  base_config:
    name: "byol_{time}"
  sac_config:
    siamese: BYOL

atc_q:
  base_config:
    name: "atc_q_{time}"
  sac_config:
    siamese: ATC
    siamese_use_q: true

byol_q:
  base_config:
    name: "byol_q_{time}"
  sac_config:
    siamese: BYOL
    siamese_use_q: true

atc_q_ada:
  base_config:
    name: "atc_q_ada_{time}"
  sac_config:
    siamese: ATC
    siamese_use_q: true
    siamese_use_adaptive: true

byol_q_ada:
  base_config:
    name: "byol_q_ada_{time}"
  sac_config:
    siamese: BYOL
    siamese_use_q: true
    siamese_use_adaptive: true

depth:
  nn_config:
    rep:
      blur: 0
      brightness: 1
      depth_blur: 0
      depth_brightness: 1
      ray_random: 0
      need_speed: true
  sac_config:
    nn: nn_depth

depth_atc:
  inherited:
    - atc
    - depth

depth_byol:
  inherited:
    - byol
    - depth

depth_atc_q:
  inherited:
    - atc_q
    - depth

depth_byol_q:
  inherited:
    - byol_q
    - depth

depth_atc_q_ada:
  inherited:
    - atc_q_ada
    - depth

depth_byol_q_ada:
  inherited:
    - byol_q_ada
    - depth
