default:
  base_config:
    env_type: GYM
    scene: Walker2D

    build_path: 'Walker2DBulletEnv-v0'

    max_step: -1
    max_iter: 10000
    save_model_per_iter: 100
    n_agents: 10

  sac_config:
    seed: 42

    n_step: 3

    _lambda: 0.99
    # use_reward_normalization: true