base_config:
  build_path: 
    win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
    linux: /data/linux-RL-Envs/RL-Envs.x86_64
  scene: RayRoller

  max_iter: 5000
  save_model_per_iter: 50
  reset_on_iteration: true
  
sac_config:
  seed: 42

  burn_in_step: 15
  n_step: 5
  use_rnn: true
  use_prediction: false

  _lambda: 0.99
  init_log_alpha: -4.6
  use_priority: true
  use_n_step_is: true