default:
  base_config:
    env_type: UNITY
    env_name: USVEscort
    unity_args: # Specific for Unity Environments
      build_path:
        win32: C:\Users\fisher\Documents\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    offline_env_config:
      enabled: true
      env_name: USVEscort
      env_args:
        dataset_path:
          win32: C:\Users\fisher\Documents\Unity\Demonstrations\USVEscort
          linux: /data/demonstrations/USVEscort

    n_envs: 10

  sac_config:
    write_summary_per_step: 500 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    seq_encoder: RNN

    offline_loss: true

  ma_config:
    USVGuard?team=0:
      sac_config:
        nn: nn
    USVPatrol?team=0:
      sac_config:
        nn: nn_patrol
    USVStrike?team=0:
      sac_config:
        nn: nn
