default:
  base_config:
    build_path:
      win32: C:\Users\Fisher\Nextcloud\Documents\Unity\win-RL-Envs\RL-Envs.exe
      linux: /data/linux-RL-Envs/RL-Envs.x86_64

    scene: Antisubmarine

    update_policy_variables_per_step: 20
    noise_increasing_rate: 0.01

    n_agents: 10

    evolver_cem_time: 8

  net_config:
    evolver_host: antisub-ds-evolver
    learner_host: antisub-ds-lr
    replay_host: antisub-ds-lr

  reset_config:
    force_reset: true

  sac_config:
    save_model_per_step: 10000 # Save model every N steps
    save_model_per_minute: 20 # Save model every N minutes

    ensemble_q_num: 10

    use_rnn: true
    use_prediction: true

    random_params:
      n_step:
        in: [4, 5, 6]
      burn_in_step:
        in: [5, 10, 15]
      v_rho:
        truncated: [0.9, 1.3]
      v_c:
        truncated: [0.9, 1.3]

  replay_config:
    batch_size: 1024

nn2:
  base_config:
    scene: Antisubmarine2
    nn: nn2
  sac_config:
    discrete_dqn_like: true
