default:
  base_config:
    build_path:
      win32: C:\Users\Fisher\Nextcloud\Documents\Unity\win-RL-Envs\RL-Envs.exe
      linux: /data/linux-RL-Envs/RL-Envs.x86_64

    scene: Antisubmarine
    reset_on_iteration: false
    n_agents: 10

  reset_config:
    force_reset: true

  sac_config:
    seed: 42
    burn_in_step: 20
    n_step: 3
    use_rnn: true
    use_prediction: true
    init_log_alpha: 0.
