default:
  base_config:
    build_path:
      win32: C:\Users\Fisher\Nextcloud\Documents\Unity\win-RL-Envs\RL-Envs.exe
      linux: /data/linux-RL-Envs/RL-Envs.x86_64

    scene: Antisubmarine
    n_agents: 10

  reset_config:
    force_reset: true

  sac_config:
    save_model_per_step: 1000

    burn_in_step: 10
    n_step: 3
    use_rnn: true
    use_prediction: true

vanilla:
  base_config:
    name: "vanilla_{time}"
    nn: "nn_vanilla"

  sac_config:
    use_rnn: false
    burn_in_step: 0
    use_prediction: false
    clip_epsilon: 1.
    # use_rnd: true
    # rnd_n_sample: 30
