default:
  base_config:
    env_type: GYM
    scene: Humanoid

    build_path: "HumanoidBulletEnv-v0"

    max_iter: -1
    n_agents: 10

  sac_config:
    write_summary_per_step: 100 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps
    save_model_per_minute: 20 # Save model every N minutes

    ensemble_q_num: 5

    use_normalization: true

hard:
  base_config: &hard_base
    scene: HumanoidHard
    nn: nn_hard

  sac_config: &hard_sac
    burn_in_step: 20
    use_rnn: true
    use_prediction: true

hard_noextra:
  base_config:
    <<: *hard_base
    name: "noextra_{time}"

  sac_config:
    <<: *hard_sac
    use_extra_data: false

hard_nopre:
  base_config:
    <<: *hard_base
    name: "nopre_{time}"

  sac_config:
    <<: *hard_sac
    use_prediction: false
