default:
  base_config:
    env_type: GYM
    env_name: HumanoidBulletEnv-v0

    noise_increasing_rate: 0.01

    n_agents: 10

    evolver_cem_time: 8

  net_config:
    evolver_host: human-ds-evolver

  sac_config:
    write_summary_per_step: 100 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    ensemble_q_num: 5

    batch_size: 1024

    n_step: 3

hard:
  base_config: &hard_base
    scene: HumanoidHard
    nn: nn_hard

  net_config:
    evolver_host: human-hard-ds-evolver

  sac_config: &hard_sac
    seq_encoder: RNN
    use_prediction: true

    random_params:
      n_step:
        in: [3, 4, 5]
      burn_in_step:
        in: [10, 20, 30]
      v_rho:
        truncated: [1.0, 2.0]
      v_c:
        truncated: [1.0, 2.0]
