default:
  base_config:
    env_type: GYM
    scene: Humanoid

    build_path: "HumanoidBulletEnv-v0"

    n_agents: 10

  net_config:
    replay_host: 127.0.0.1
    replay_port: 61000
    learner_host: 127.0.0.1
    learner_port: 61001

  sac_config:
    write_summary_per_step: 100 # Write summaries in TensorBoard every N steps
    save_model_per_step: 100000 # Save model every N steps
    save_model_per_minute: 5 # Save model every N minutes

    init_log_alpha: 0.
    n_step: 3
    clip_epsilon: 1.
    learning_rate: 0.0001

    # use_curiosity: true
    # curiosity_strength: 0.6

  replay_config:
    batch_size: 1024
    capacity: 1048576
    td_error_max: 5. # Clipped abs error

hard:
  base_config: &hard_base
    scene: Walker2DHard
    sac: sac_hard

  sac_config: &hard_sac
    burn_in_step: 20
    use_rnn: true
    use_prediction: true
