default:
  base_config:
    scene: RaspiCar

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    no_graphics: false

    n_agents: 10
    reset_on_iteration: false

  reset_config:
    force_reset: true

  model_config:
    rep:
      blur: 0
      brightness: 1
      need_ray: true
      need_speed: true

  sac_config:
    write_summary_per_step: 500 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    use_rnn: true

    use_contrastive: true

    use_rnd: true
    rnd_n_sample: 50

bl0br2ray1sp1:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      need_ray: true
      need_speed: true
bl0br2ray1sp0:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      need_ray: true
      need_speed: false
bl0br2ray0sp1:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      need_ray: false
      need_speed: true
bl0br2ray0sp0:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      need_ray: false
      need_speed: false
bl0br5ray1sp1:
  model_config:
    rep:
      blur: 0
      brightness: 0.5
      need_ray: true
      need_speed: true
bl0br5ray1sp0:
  model_config:
    rep:
      blur: 0
      brightness: 0.5
      need_ray: true
      need_speed: false
bl0br5ray0sp1:
  model_config:
    rep:
      blur: 0
      brightness: 0.5
      need_ray: false
      need_speed: true
bl0br5ray0sp0:
  model_config:
    rep:
      blur: 0
      brightness: 0.5
      need_ray: false
      need_speed: false
bl0br8ray1sp1:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      need_ray: true
      need_speed: true
bl0br8ray1sp0:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      need_ray: true
      need_speed: false
bl0br8ray0sp1:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      need_ray: false
      need_speed: true
bl0br8ray0sp0:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      need_ray: false
      need_speed: false
bl0br10ray1sp1:
  model_config:
    rep:
      blur: 0
      brightness: 1
      need_ray: true
      need_speed: true
bl0br10ray1sp0:
  model_config:
    rep:
      blur: 0
      brightness: 1
      need_ray: true
      need_speed: false
bl0br10ray0sp1:
  model_config:
    rep:
      blur: 0
      brightness: 1
      need_ray: false
      need_speed: true
bl0br10ray0sp0:
  model_config:
    rep:
      blur: 0
      brightness: 1
      need_ray: false
      need_speed: false
bl0br12ray1sp1:
  model_config:
    rep:
      blur: 0
      brightness: 1.2
      need_ray: true
      need_speed: true
bl0br12ray1sp0:
  model_config:
    rep:
      blur: 0
      brightness: 1.2
      need_ray: true
      need_speed: false
bl0br12ray0sp1:
  model_config:
    rep:
      blur: 0
      brightness: 1.2
      need_ray: false
      need_speed: true
bl0br12ray0sp0:
  model_config:
    rep:
      blur: 0
      brightness: 1.2
      need_ray: false
      need_speed: false
bl3br2ray1sp1:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      need_ray: true
      need_speed: true
bl3br2ray1sp0:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      need_ray: true
      need_speed: false
bl3br2ray0sp1:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      need_ray: false
      need_speed: true
bl3br2ray0sp0:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      need_ray: false
      need_speed: false
bl3br5ray1sp1:
  model_config:
    rep:
      blur: 3
      brightness: 0.5
      need_ray: true
      need_speed: true
bl3br5ray1sp0:
  model_config:
    rep:
      blur: 3
      brightness: 0.5
      need_ray: true
      need_speed: false
bl3br5ray0sp1:
  model_config:
    rep:
      blur: 3
      brightness: 0.5
      need_ray: false
      need_speed: true
bl3br5ray0sp0:
  model_config:
    rep:
      blur: 3
      brightness: 0.5
      need_ray: false
      need_speed: false
bl3br8ray1sp1:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      need_ray: true
      need_speed: true
bl3br8ray1sp0:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      need_ray: true
      need_speed: false
bl3br8ray0sp1:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      need_ray: false
      need_speed: true
bl3br8ray0sp0:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      need_ray: false
      need_speed: false
bl3br10ray1sp1:
  model_config:
    rep:
      blur: 3
      brightness: 1
      need_ray: true
      need_speed: true
bl3br10ray1sp0:
  model_config:
    rep:
      blur: 3
      brightness: 1
      need_ray: true
      need_speed: false
bl3br10ray0sp1:
  model_config:
    rep:
      blur: 3
      brightness: 1
      need_ray: false
      need_speed: true
bl3br10ray0sp0:
  model_config:
    rep:
      blur: 3
      brightness: 1
      need_ray: false
      need_speed: false
bl3br12ray1sp1:
  model_config:
    rep:
      blur: 3
      brightness: 1.2
      need_ray: true
      need_speed: true
bl3br12ray1sp0:
  model_config:
    rep:
      blur: 3
      brightness: 1.2
      need_ray: true
      need_speed: false
bl3br12ray0sp1:
  model_config:
    rep:
      blur: 3
      brightness: 1.2
      need_ray: false
      need_speed: true
bl3br12ray0sp0:
  model_config:
    rep:
      blur: 3
      brightness: 1.2
      need_ray: false
      need_speed: false
bl5br2ray1sp1:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      need_ray: true
      need_speed: true
bl5br2ray1sp0:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      need_ray: true
      need_speed: false
bl5br2ray0sp1:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      need_ray: false
      need_speed: true
bl5br2ray0sp0:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      need_ray: false
      need_speed: false
bl5br5ray1sp1:
  model_config:
    rep:
      blur: 5
      brightness: 0.5
      need_ray: true
      need_speed: true
bl5br5ray1sp0:
  model_config:
    rep:
      blur: 5
      brightness: 0.5
      need_ray: true
      need_speed: false
bl5br5ray0sp1:
  model_config:
    rep:
      blur: 5
      brightness: 0.5
      need_ray: false
      need_speed: true
bl5br5ray0sp0:
  model_config:
    rep:
      blur: 5
      brightness: 0.5
      need_ray: false
      need_speed: false
bl5br8ray1sp1:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      need_ray: true
      need_speed: true
bl5br8ray1sp0:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      need_ray: true
      need_speed: false
bl5br8ray0sp1:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      need_ray: false
      need_speed: true
bl5br8ray0sp0:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      need_ray: false
      need_speed: false
bl5br10ray1sp1:
  model_config:
    rep:
      blur: 5
      brightness: 1
      need_ray: true
      need_speed: true
bl5br10ray1sp0:
  model_config:
    rep:
      blur: 5
      brightness: 1
      need_ray: true
      need_speed: false
bl5br10ray0sp1:
  model_config:
    rep:
      blur: 5
      brightness: 1
      need_ray: false
      need_speed: true
bl5br10ray0sp0:
  model_config:
    rep:
      blur: 5
      brightness: 1
      need_ray: false
      need_speed: false
bl5br12ray1sp1:
  model_config:
    rep:
      blur: 5
      brightness: 1.2
      need_ray: true
      need_speed: true
bl5br12ray1sp0:
  model_config:
    rep:
      blur: 5
      brightness: 1.2
      need_ray: true
      need_speed: false
bl5br12ray0sp1:
  model_config:
    rep:
      blur: 5
      brightness: 1.2
      need_ray: false
      need_speed: true
bl5br12ray0sp0:
  model_config:
    rep:
      blur: 5
      brightness: 1.2
      need_ray: false
      need_speed: false
bl9br2ray1sp1:
  model_config:
    rep:
      blur: 9
      brightness: 0.2
      need_ray: true
      need_speed: true
bl9br2ray1sp0:
  model_config:
    rep:
      blur: 9
      brightness: 0.2
      need_ray: true
      need_speed: false
bl9br2ray0sp1:
  model_config:
    rep:
      blur: 9
      brightness: 0.2
      need_ray: false
      need_speed: true
bl9br2ray0sp0:
  model_config:
    rep:
      blur: 9
      brightness: 0.2
      need_ray: false
      need_speed: false
bl9br5ray1sp1:
  model_config:
    rep:
      blur: 9
      brightness: 0.5
      need_ray: true
      need_speed: true
bl9br5ray1sp0:
  model_config:
    rep:
      blur: 9
      brightness: 0.5
      need_ray: true
      need_speed: false
bl9br5ray0sp1:
  model_config:
    rep:
      blur: 9
      brightness: 0.5
      need_ray: false
      need_speed: true
bl9br5ray0sp0:
  model_config:
    rep:
      blur: 9
      brightness: 0.5
      need_ray: false
      need_speed: false
bl9br8ray1sp1:
  model_config:
    rep:
      blur: 9
      brightness: 0.8
      need_ray: true
      need_speed: true
bl9br8ray1sp0:
  model_config:
    rep:
      blur: 9
      brightness: 0.8
      need_ray: true
      need_speed: false
bl9br8ray0sp1:
  model_config:
    rep:
      blur: 9
      brightness: 0.8
      need_ray: false
      need_speed: true
bl9br8ray0sp0:
  model_config:
    rep:
      blur: 9
      brightness: 0.8
      need_ray: false
      need_speed: false
bl9br10ray1sp1:
  model_config:
    rep:
      blur: 9
      brightness: 1
      need_ray: true
      need_speed: true
bl9br10ray1sp0:
  model_config:
    rep:
      blur: 9
      brightness: 1
      need_ray: true
      need_speed: false
bl9br10ray0sp1:
  model_config:
    rep:
      blur: 9
      brightness: 1
      need_ray: false
      need_speed: true
bl9br10ray0sp0:
  model_config:
    rep:
      blur: 9
      brightness: 1
      need_ray: false
      need_speed: false
bl9br12ray1sp1:
  model_config:
    rep:
      blur: 9
      brightness: 1.2
      need_ray: true
      need_speed: true
bl9br12ray1sp0:
  model_config:
    rep:
      blur: 9
      brightness: 1.2
      need_ray: true
      need_speed: false
bl9br12ray0sp1:
  model_config:
    rep:
      blur: 9
      brightness: 1.2
      need_ray: false
      need_speed: true
bl9br12ray0sp0:
  model_config:
    rep:
      blur: 9
      brightness: 1.2
      need_ray: false
      need_speed: false
