default:
  base_config:
    scene: AvoidCar

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    no_graphics: false

    n_agents: 10
    reset_on_iteration: false

  reset_config:
    force_reset: true
    bounding_box_random: 0

  sac_config:
    write_summary_per_step: 1000

    n_step: 3
    use_rnd: true
    rnd_n_sample: 50

r5:
  reset_config:
    bounding_box_random: 5

r10:
  reset_config:
    bounding_box_random: 10

r15:
  reset_config:
    bounding_box_random: 15
