default:
  base_config:
    scene: RosCar

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    no_graphics: false

    n_agents: 10
    reset_on_iteration: false

  reset_config:
    force_reset: true

  model_config:
    rep:
      blur: 0
      brightness: 1
      need_ray: true
      need_speed: true

  sac_config:
    write_summary_per_step: 500 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    use_rnn: true

    use_rnd: true
    rnd_n_sample: 50

simclr:
  base_config:
    name: simclr_{time}
  sac_config:
    siamese: SIMCLR

byol:
  base_config:
    name: byol_{time}
  sac_config:
    siamese: BYOL

simsiam:
  base_config:
    name: simsiam_{time}
  sac_config:
    siamese: SIMSIAM

simclr_ada:
  base_config:
    name: simclr_ada_{time}
  sac_config:
    siamese: SIMCLR
    siamese_use_adaptive: true

byol_ada:
  base_config:
    name: byol_ada_{time}
  sac_config:
    siamese: BYOL
    siamese_use_adaptive: true

simsiam_ada:
  base_config:
    name: simsiam_ada_{time}
  sac_config:
    siamese: SIMSIAM
    siamese_use_adaptive: true
