default:
  base_config:
    scene: RosCar

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    no_graphics: false

    n_agents: 10
    reset_on_iteration: false

  reset_config:
    force_reset: true

  model_config:
    rep:
      blur: 0
      brightness: 1
      ray_random: 200
      need_speed: true

  sac_config:
    write_summary_per_step: 500 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    use_rnn: true

    use_rnd: true
    rnd_n_sample: 50

atc:
  base_config:
    name: "atc_{time}"
  sac_config:
    siamese: ATC

byol:
  base_config:
    name: "byol_{time}"
  sac_config:
    siamese: BYOL

ray0:
  model_config:
    rep:
      ray_random: 0

ray50:
  model_config:
    rep:
      ray_random: 50

ray100:
  model_config:
    rep:
      ray_random: 100

ray150:
  model_config:
    rep:
      ray_random: 150

ray200:
  model_config:
    rep:
      ray_random: 200

ray250:
  model_config:
    rep:
      ray_random: 250

ray300:
  model_config:
    rep:
      ray_random: 300

ray350:
  model_config:
    rep:
      ray_random: 350

ray400:
  model_config:
    rep:
      ray_random: 400

ray450:
  model_config:
    rep:
      ray_random: 450

ray500:
  model_config:
    rep:
      ray_random: 500

ray550:
  model_config:
    rep:
      ray_random: 550

ray600:
  model_config:
    rep:
      ray_random: 600
