default:
  base_config:
    env_name: RosCar
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    n_agents: 50
    max_step: 300000
    reset_on_iteration: false

  reset_config:
    force_reset: true
    bounding_box_random: 0
    semantic_segmentation_random: 0

  nn_config:
    rep:
      blur: 0
      brightness: 1
      ray_random: 0
      need_speed: true

  sac_config:
    write_summary_per_step: 500 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    seq_encoder: RNN

    use_rnd: true
    rnd_n_sample: 50

atc:
  base_config:
    name: "atc_{time}"
  sac_config:
    siamese: ATC

byol:
  base_config:
    name: "byol_{time}"
  sac_config:
    siamese: BYOL

atc_q:
  base_config:
    name: "atc_q_{time}"
  sac_config:
    siamese: ATC
    siamese_use_q: true

byol_q:
  base_config:
    name: "byol_q_{time}"
  sac_config:
    siamese: BYOL
    siamese_use_q: true

atc_q_ada:
  base_config:
    name: "atc_q_ada_{time}"
  sac_config:
    siamese: ATC
    siamese_use_q: true
    siamese_use_adaptive: true

byol_q_ada:
  base_config:
    name: "byol_q_ada_{time}"
  sac_config:
    siamese: BYOL
    siamese_use_q: true
    siamese_use_adaptive: true

ray_0_blur_0_brightness_0.2:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      ray_random: 0

ray_0_blur_0_brightness_0.4:
  model_config:
    rep:
      blur: 0
      brightness: 0.4
      ray_random: 0

ray_0_blur_0_brightness_0.6:
  model_config:
    rep:
      blur: 0
      brightness: 0.6
      ray_random: 0

ray_0_blur_0_brightness_0.8:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      ray_random: 0

ray_0_blur_0_brightness_1.0:
  model_config:
    rep:
      blur: 0
      brightness: 1.0
      ray_random: 0

ray_0_blur_3_brightness_0.2:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      ray_random: 0

ray_0_blur_3_brightness_0.4:
  model_config:
    rep:
      blur: 3
      brightness: 0.4
      ray_random: 0

ray_0_blur_3_brightness_0.6:
  model_config:
    rep:
      blur: 3
      brightness: 0.6
      ray_random: 0

ray_0_blur_3_brightness_0.8:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      ray_random: 0

ray_0_blur_3_brightness_1.0:
  model_config:
    rep:
      blur: 3
      brightness: 1.0
      ray_random: 0

ray_0_blur_5_brightness_0.2:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      ray_random: 0

ray_0_blur_5_brightness_0.4:
  model_config:
    rep:
      blur: 5
      brightness: 0.4
      ray_random: 0

ray_0_blur_5_brightness_0.6:
  model_config:
    rep:
      blur: 5
      brightness: 0.6
      ray_random: 0

ray_0_blur_5_brightness_0.8:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      ray_random: 0

ray_0_blur_5_brightness_1.0:
  model_config:
    rep:
      blur: 5
      brightness: 1.0
      ray_random: 0

ray_0_blur_7_brightness_0.2:
  model_config:
    rep:
      blur: 7
      brightness: 0.2
      ray_random: 0

ray_0_blur_7_brightness_0.4:
  model_config:
    rep:
      blur: 7
      brightness: 0.4
      ray_random: 0

ray_0_blur_7_brightness_0.6:
  model_config:
    rep:
      blur: 7
      brightness: 0.6
      ray_random: 0

ray_0_blur_7_brightness_0.8:
  model_config:
    rep:
      blur: 7
      brightness: 0.8
      ray_random: 0

ray_0_blur_7_brightness_1.0:
  model_config:
    rep:
      blur: 7
      brightness: 1.0
      ray_random: 0

ray_50_blur_0_brightness_0.2:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      ray_random: 50

ray_50_blur_0_brightness_0.4:
  model_config:
    rep:
      blur: 0
      brightness: 0.4
      ray_random: 50

ray_50_blur_0_brightness_0.6:
  model_config:
    rep:
      blur: 0
      brightness: 0.6
      ray_random: 50

ray_50_blur_0_brightness_0.8:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      ray_random: 50

ray_50_blur_0_brightness_1.0:
  model_config:
    rep:
      blur: 0
      brightness: 1.0
      ray_random: 50

ray_50_blur_3_brightness_0.2:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      ray_random: 50

ray_50_blur_3_brightness_0.4:
  model_config:
    rep:
      blur: 3
      brightness: 0.4
      ray_random: 50

ray_50_blur_3_brightness_0.6:
  model_config:
    rep:
      blur: 3
      brightness: 0.6
      ray_random: 50

ray_50_blur_3_brightness_0.8:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      ray_random: 50

ray_50_blur_3_brightness_1.0:
  model_config:
    rep:
      blur: 3
      brightness: 1.0
      ray_random: 50

ray_50_blur_5_brightness_0.2:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      ray_random: 50

ray_50_blur_5_brightness_0.4:
  model_config:
    rep:
      blur: 5
      brightness: 0.4
      ray_random: 50

ray_50_blur_5_brightness_0.6:
  model_config:
    rep:
      blur: 5
      brightness: 0.6
      ray_random: 50

ray_50_blur_5_brightness_0.8:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      ray_random: 50

ray_50_blur_5_brightness_1.0:
  model_config:
    rep:
      blur: 5
      brightness: 1.0
      ray_random: 50

ray_50_blur_7_brightness_0.2:
  model_config:
    rep:
      blur: 7
      brightness: 0.2
      ray_random: 50

ray_50_blur_7_brightness_0.4:
  model_config:
    rep:
      blur: 7
      brightness: 0.4
      ray_random: 50

ray_50_blur_7_brightness_0.6:
  model_config:
    rep:
      blur: 7
      brightness: 0.6
      ray_random: 50

ray_50_blur_7_brightness_0.8:
  model_config:
    rep:
      blur: 7
      brightness: 0.8
      ray_random: 50

ray_50_blur_7_brightness_1.0:
  model_config:
    rep:
      blur: 7
      brightness: 1.0
      ray_random: 50

ray_100_blur_0_brightness_0.2:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      ray_random: 100

ray_100_blur_0_brightness_0.4:
  model_config:
    rep:
      blur: 0
      brightness: 0.4
      ray_random: 100

ray_100_blur_0_brightness_0.6:
  model_config:
    rep:
      blur: 0
      brightness: 0.6
      ray_random: 100

ray_100_blur_0_brightness_0.8:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      ray_random: 100

ray_100_blur_0_brightness_1.0:
  model_config:
    rep:
      blur: 0
      brightness: 1.0
      ray_random: 100

ray_100_blur_3_brightness_0.2:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      ray_random: 100

ray_100_blur_3_brightness_0.4:
  model_config:
    rep:
      blur: 3
      brightness: 0.4
      ray_random: 100

ray_100_blur_3_brightness_0.6:
  model_config:
    rep:
      blur: 3
      brightness: 0.6
      ray_random: 100

ray_100_blur_3_brightness_0.8:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      ray_random: 100

ray_100_blur_3_brightness_1.0:
  model_config:
    rep:
      blur: 3
      brightness: 1.0
      ray_random: 100

ray_100_blur_5_brightness_0.2:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      ray_random: 100

ray_100_blur_5_brightness_0.4:
  model_config:
    rep:
      blur: 5
      brightness: 0.4
      ray_random: 100

ray_100_blur_5_brightness_0.6:
  model_config:
    rep:
      blur: 5
      brightness: 0.6
      ray_random: 100

ray_100_blur_5_brightness_0.8:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      ray_random: 100

ray_100_blur_5_brightness_1.0:
  model_config:
    rep:
      blur: 5
      brightness: 1.0
      ray_random: 100

ray_100_blur_7_brightness_0.2:
  model_config:
    rep:
      blur: 7
      brightness: 0.2
      ray_random: 100

ray_100_blur_7_brightness_0.4:
  model_config:
    rep:
      blur: 7
      brightness: 0.4
      ray_random: 100

ray_100_blur_7_brightness_0.6:
  model_config:
    rep:
      blur: 7
      brightness: 0.6
      ray_random: 100

ray_100_blur_7_brightness_0.8:
  model_config:
    rep:
      blur: 7
      brightness: 0.8
      ray_random: 100

ray_100_blur_7_brightness_1.0:
  model_config:
    rep:
      blur: 7
      brightness: 1.0
      ray_random: 100

ray_150_blur_0_brightness_0.2:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      ray_random: 150

ray_150_blur_0_brightness_0.4:
  model_config:
    rep:
      blur: 0
      brightness: 0.4
      ray_random: 150

ray_150_blur_0_brightness_0.6:
  model_config:
    rep:
      blur: 0
      brightness: 0.6
      ray_random: 150

ray_150_blur_0_brightness_0.8:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      ray_random: 150

ray_150_blur_0_brightness_1.0:
  model_config:
    rep:
      blur: 0
      brightness: 1.0
      ray_random: 150

ray_150_blur_3_brightness_0.2:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      ray_random: 150

ray_150_blur_3_brightness_0.4:
  model_config:
    rep:
      blur: 3
      brightness: 0.4
      ray_random: 150

ray_150_blur_3_brightness_0.6:
  model_config:
    rep:
      blur: 3
      brightness: 0.6
      ray_random: 150

ray_150_blur_3_brightness_0.8:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      ray_random: 150

ray_150_blur_3_brightness_1.0:
  model_config:
    rep:
      blur: 3
      brightness: 1.0
      ray_random: 150

ray_150_blur_5_brightness_0.2:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      ray_random: 150

ray_150_blur_5_brightness_0.4:
  model_config:
    rep:
      blur: 5
      brightness: 0.4
      ray_random: 150

ray_150_blur_5_brightness_0.6:
  model_config:
    rep:
      blur: 5
      brightness: 0.6
      ray_random: 150

ray_150_blur_5_brightness_0.8:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      ray_random: 150

ray_150_blur_5_brightness_1.0:
  model_config:
    rep:
      blur: 5
      brightness: 1.0
      ray_random: 150

ray_150_blur_7_brightness_0.2:
  model_config:
    rep:
      blur: 7
      brightness: 0.2
      ray_random: 150

ray_150_blur_7_brightness_0.4:
  model_config:
    rep:
      blur: 7
      brightness: 0.4
      ray_random: 150

ray_150_blur_7_brightness_0.6:
  model_config:
    rep:
      blur: 7
      brightness: 0.6
      ray_random: 150

ray_150_blur_7_brightness_0.8:
  model_config:
    rep:
      blur: 7
      brightness: 0.8
      ray_random: 150

ray_150_blur_7_brightness_1.0:
  model_config:
    rep:
      blur: 7
      brightness: 1.0
      ray_random: 150

ray_200_blur_0_brightness_0.2:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      ray_random: 200

ray_200_blur_0_brightness_0.4:
  model_config:
    rep:
      blur: 0
      brightness: 0.4
      ray_random: 200

ray_200_blur_0_brightness_0.6:
  model_config:
    rep:
      blur: 0
      brightness: 0.6
      ray_random: 200

ray_200_blur_0_brightness_0.8:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      ray_random: 200

ray_200_blur_0_brightness_1.0:
  model_config:
    rep:
      blur: 0
      brightness: 1.0
      ray_random: 200

ray_200_blur_3_brightness_0.2:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      ray_random: 200

ray_200_blur_3_brightness_0.4:
  model_config:
    rep:
      blur: 3
      brightness: 0.4
      ray_random: 200

ray_200_blur_3_brightness_0.6:
  model_config:
    rep:
      blur: 3
      brightness: 0.6
      ray_random: 200

ray_200_blur_3_brightness_0.8:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      ray_random: 200

ray_200_blur_3_brightness_1.0:
  model_config:
    rep:
      blur: 3
      brightness: 1.0
      ray_random: 200

ray_200_blur_5_brightness_0.2:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      ray_random: 200

ray_200_blur_5_brightness_0.4:
  model_config:
    rep:
      blur: 5
      brightness: 0.4
      ray_random: 200

ray_200_blur_5_brightness_0.6:
  model_config:
    rep:
      blur: 5
      brightness: 0.6
      ray_random: 200

ray_200_blur_5_brightness_0.8:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      ray_random: 200

ray_200_blur_5_brightness_1.0:
  model_config:
    rep:
      blur: 5
      brightness: 1.0
      ray_random: 200

ray_200_blur_7_brightness_0.2:
  model_config:
    rep:
      blur: 7
      brightness: 0.2
      ray_random: 200

ray_200_blur_7_brightness_0.4:
  model_config:
    rep:
      blur: 7
      brightness: 0.4
      ray_random: 200

ray_200_blur_7_brightness_0.6:
  model_config:
    rep:
      blur: 7
      brightness: 0.6
      ray_random: 200

ray_200_blur_7_brightness_0.8:
  model_config:
    rep:
      blur: 7
      brightness: 0.8
      ray_random: 200

ray_200_blur_7_brightness_1.0:
  model_config:
    rep:
      blur: 7
      brightness: 1.0
      ray_random: 200

ray_300_blur_0_brightness_0.2:
  model_config:
    rep:
      blur: 0
      brightness: 0.2
      ray_random: 300

ray_300_blur_0_brightness_0.4:
  model_config:
    rep:
      blur: 0
      brightness: 0.4
      ray_random: 300

ray_300_blur_0_brightness_0.6:
  model_config:
    rep:
      blur: 0
      brightness: 0.6
      ray_random: 300

ray_300_blur_0_brightness_0.8:
  model_config:
    rep:
      blur: 0
      brightness: 0.8
      ray_random: 300

ray_300_blur_0_brightness_1.0:
  model_config:
    rep:
      blur: 0
      brightness: 1.0
      ray_random: 300

ray_300_blur_3_brightness_0.2:
  model_config:
    rep:
      blur: 3
      brightness: 0.2
      ray_random: 300

ray_300_blur_3_brightness_0.4:
  model_config:
    rep:
      blur: 3
      brightness: 0.4
      ray_random: 300

ray_300_blur_3_brightness_0.6:
  model_config:
    rep:
      blur: 3
      brightness: 0.6
      ray_random: 300

ray_300_blur_3_brightness_0.8:
  model_config:
    rep:
      blur: 3
      brightness: 0.8
      ray_random: 300

ray_300_blur_3_brightness_1.0:
  model_config:
    rep:
      blur: 3
      brightness: 1.0
      ray_random: 300

ray_300_blur_5_brightness_0.2:
  model_config:
    rep:
      blur: 5
      brightness: 0.2
      ray_random: 300

ray_300_blur_5_brightness_0.4:
  model_config:
    rep:
      blur: 5
      brightness: 0.4
      ray_random: 300

ray_300_blur_5_brightness_0.6:
  model_config:
    rep:
      blur: 5
      brightness: 0.6
      ray_random: 300

ray_300_blur_5_brightness_0.8:
  model_config:
    rep:
      blur: 5
      brightness: 0.8
      ray_random: 300

ray_300_blur_5_brightness_1.0:
  model_config:
    rep:
      blur: 5
      brightness: 1.0
      ray_random: 300

ray_300_blur_7_brightness_0.2:
  model_config:
    rep:
      blur: 7
      brightness: 0.2
      ray_random: 300

ray_300_blur_7_brightness_0.4:
  model_config:
    rep:
      blur: 7
      brightness: 0.4
      ray_random: 300

ray_300_blur_7_brightness_0.6:
  model_config:
    rep:
      blur: 7
      brightness: 0.6
      ray_random: 300

ray_300_blur_7_brightness_0.8:
  model_config:
    rep:
      blur: 7
      brightness: 0.8
      ray_random: 300

ray_300_blur_7_brightness_1.0:
  model_config:
    rep:
      blur: 7
      brightness: 1.0
      ray_random: 300
