default:
  base_config:
    env_type: GYM
    env_name: HalfCheetahBulletEnv-v0

    max_iter: -1
    max_step: 500000
    n_agents: 10

  sac_config:
    write_summary_per_step: 100 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    init_log_alpha: 0.

    n_step: 1
    v_lambda: 0.99

    use_rnd: true
    rnd_n_sample: 50

    # use_normalization: true

hard:
  base_config: &hard_base
    scene: HalfCheetahHard
    nn: nn_hard

  sac_config: &hard_sac
    burn_in_step: 30
    seq_encoder: RNN
    use_prediction: true

hard_noextra:
  base_config:
    <<: *hard_base
    name: "noextra_{time}"

  sac_config:
    <<: *hard_sac
    use_extra_data: false

hard_nopre:
  base_config:
    <<: *hard_base
    name: "nopre_{time}"

  sac_config:
    <<: *hard_sac
    use_prediction: false
