default:
  base_config:
    scene: USV

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    no_graphics: false

    n_agents: 10
    reset_on_iteration: false

  reset_config:
    spectrum: 3
    force_reset: true
    bounding_box_random: 0
    semantic_segmentation_random: 0

  sac_config:
    write_summary_per_step: 1000

    n_step: 3
    burn_in_step: 10
    use_rnn: true
    use_rnd: true
    rnd_n_sample: 50

br0sr0:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 0
br0sr2:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 2
br0sr4:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 4
br0sr6:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 6
br0sr8:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 8
br0sr10:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 10
br0sr12:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 12
br0sr14:
  reset_config:
    bounding_box_random: 0
    semantic_segmentation_random: 14
br2sr0:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 0
br2sr2:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 2
br2sr4:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 4
br2sr6:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 6
br2sr8:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 8
br2sr10:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 10
br2sr12:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 12
br2sr14:
  reset_config:
    bounding_box_random: 2
    semantic_segmentation_random: 14
br4sr0:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 0
br4sr2:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 2
br4sr4:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 4
br4sr6:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 6
br4sr8:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 8
br4sr10:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 10
br4sr12:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 12
br4sr14:
  reset_config:
    bounding_box_random: 4
    semantic_segmentation_random: 14
br6sr0:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 0
br6sr2:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 2
br6sr4:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 4
br6sr6:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 6
br6sr8:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 8
br6sr10:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 10
br6sr12:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 12
br6sr14:
  reset_config:
    bounding_box_random: 6
    semantic_segmentation_random: 14
br8sr0:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 0
br8sr2:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 2
br8sr4:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 4
br8sr6:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 6
br8sr8:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 8
br8sr10:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 10
br8sr12:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 12
br8sr14:
  reset_config:
    bounding_box_random: 8
    semantic_segmentation_random: 14
br10sr0:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 0
br10sr2:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 2
br10sr4:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 4
br10sr6:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 6
br10sr8:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 8
br10sr10:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 10
br10sr12:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 12
br10sr14:
  reset_config:
    bounding_box_random: 10
    semantic_segmentation_random: 14
br12sr0:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 0
br12sr2:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 2
br12sr4:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 4
br12sr6:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 6
br12sr8:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 8
br12sr10:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 10
br12sr12:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 12
br12sr14:
  reset_config:
    bounding_box_random: 12
    semantic_segmentation_random: 14
br14sr0:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 0
br14sr2:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 2
br14sr4:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 4
br14sr6:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 6
br14sr8:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 8
br14sr10:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 10
br14sr12:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 12
br14sr14:
  reset_config:
    bounding_box_random: 14
    semantic_segmentation_random: 14
