default:
  base_config:
    scene: USV

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    no_graphics: false

    n_agents: 10
    reset_on_iteration: false

  reset_config:
    force_reset: true

  sac_config:
    write_summary_per_step: 1000

    n_step: 3
    use_rnd: true
    rnd_n_sample: 50

visual:
  base_config:
    name: "vis_{time}"
    nn: nn_visual

  sac_config:
    burn_in_step: 10
    use_rnn: true

visual_nature:
  base_config:
    name: "vis_nature_{time}"
    nn: nn_visual_nature
