default:
  base_config:
    env_name: UAVSTS
    unity_args:
      build_path:
        win32: C:\Users\fisher\Documents\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    n_envs: 50
    reset_on_iteration: false

  reset_config:
    force_reset: true

  sac_config:
    write_summary_per_step: 1000 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 20
    seq_encoder: RNN

aggr:
  base_config:
    unity_args:
      group_aggregation: true

  sac_config:
    nn: nn_aggr