default:
  base_config:
    env_type: GYM
    env_name: CartPole-v1

    max_step: -1
    max_iter: 1000
    n_agents: 10

  replay_config:
    capacity: 100000
    alpha: 0.
    beta_increment_per_sampling: 0

  sac_config:
    save_model_per_step: 1000 # Save model every N steps

    learning_rate: 0.01
    batch_size: 128

    n_step: 3
    clip_epsilon: -1

    discrete_dqn_like: true

    use_n_step_is: true

no_dqn:
  sac_config:
    discrete_dqn_like: false
    learning_rate: 0.0001
