default:
  base_config:
    env_type: GYM
    scene: CartPole

    build_path: CartPole-v1

    max_step: -1
    max_iter: 1000
    save_model_per_iter: 50
    n_agents: 10

  replay_config:
    beta: 0.1
    beta_increment_per_sampling: 0

  sac_config:
    seed: 42

    n_step: 3

    _lambda: 0.99
    init_log_alpha: -4.6
    # use_reward_normalization: true