default:
  base_config:
    env_type: GYM
    scene: CartPole

    build_path: CartPole-v1

    max_step: -1
    max_iter: 1000
    n_agents: 10

  sac_config:
    save_model_per_step: 10000 # Save model every N steps
    save_model_per_minute: 1 # Save model every N minutes

    n_step: 2

    init_log_alpha: -4.6