default:
  base_config:
    env_type: GYM
    scene: CartPole

    build_path: CartPole-v1

    max_step: -1
    max_iter: 1000
    n_agents: 10

  replay_config:
    batch_size: 128
    capacity: 100000
    alpha: 0.
    beta_increment_per_sampling: 0

  sac_config:
    save_model_per_step: 1000 # Save model every N steps
    save_model_per_minute: 1 # Save model every N minutes

    # learning_rate: 0.0001

    n_step: 3
    clip_epsilon: -1

    use_n_step_is: true
