build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-simple-boat\RL-Envs.exe
  linux: /data/zzy/linux-simple-boat/RL-Envs.x86_64

# sac: sac
max_iter: 10000
# agents_num: 1
# save_model_per_iter: 500
action_idx: 0
reward_idx: 1

write_summary_graph: true
# seed: None
# gamma: 0.99
# tau: 0.005
# write_summary_per_step: 20
# update_target_per_step: 1
# init_log_alpha: -4.6
# use_auto_alpha: true
# lr: 3e-4
use_priority: false
# batch_size: 256
# replay_buffer_capacity: 1000000