# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evolver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ndarray_pb2 as ndarray__pb2
import pingpong_pb2 as pingpong__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evolver.proto',
  package='evolver',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\revolver.proto\x12\x07\x65volver\x1a\rndarray.proto\x1a\x0epingpong.proto\"D\n\x16RegisterLearnerRequest\x12\x14\n\x0clearner_host\x18\x02 \x01(\t\x12\x14\n\x0clearner_port\x18\x03 \x01(\x05\"g\n\x17RegisterLearnerResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x19\n\x11reset_config_json\x18\x03 \x01(\t\x12\x17\n\x0fsac_config_json\x18\x05 \x01(\t\"V\n\x15RegisterActorResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x14\n\x0clearner_host\x18\x02 \x01(\t\x12\x14\n\x0clearner_port\x18\x03 \x01(\x05\",\n\x1aPostRewardToEvolverRequest\x12\x0e\n\x06reward\x18\x01 \x01(\x02\"H\n\x16GetNNVariablesResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x1b\n\tvariables\x18\x02 \x03(\x0b\x32\x08.NDarray2\xb6\x02\n\x0e\x45volverService\x12\x1f\n\x0bPersistence\x12\x05.Ping\x1a\x05.Pong(\x01\x30\x01\x12T\n\x0fRegisterLearner\x12\x1f.evolver.RegisterLearnerRequest\x1a .evolver.RegisterLearnerResponse\x12\x37\n\rRegisterActor\x12\x06.Empty\x1a\x1e.evolver.RegisterActorResponse\x12\x39\n\nPostReward\x12#.evolver.PostRewardToEvolverRequest\x1a\x06.Empty\x12\x39\n\x0eGetNNVariables\x12\x06.Empty\x1a\x1f.evolver.GetNNVariablesResponseb\x06proto3'
  ,
  dependencies=[ndarray__pb2.DESCRIPTOR,pingpong__pb2.DESCRIPTOR,])




_REGISTERLEARNERREQUEST = _descriptor.Descriptor(
  name='RegisterLearnerRequest',
  full_name='evolver.RegisterLearnerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='learner_host', full_name='evolver.RegisterLearnerRequest.learner_host', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learner_port', full_name='evolver.RegisterLearnerRequest.learner_port', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=125,
)


_REGISTERLEARNERRESPONSE = _descriptor.Descriptor(
  name='RegisterLearnerResponse',
  full_name='evolver.RegisterLearnerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='evolver.RegisterLearnerResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='evolver.RegisterLearnerResponse.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reset_config_json', full_name='evolver.RegisterLearnerResponse.reset_config_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sac_config_json', full_name='evolver.RegisterLearnerResponse.sac_config_json', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=230,
)


_REGISTERACTORRESPONSE = _descriptor.Descriptor(
  name='RegisterActorResponse',
  full_name='evolver.RegisterActorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='evolver.RegisterActorResponse.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learner_host', full_name='evolver.RegisterActorResponse.learner_host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learner_port', full_name='evolver.RegisterActorResponse.learner_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=318,
)


_POSTREWARDTOEVOLVERREQUEST = _descriptor.Descriptor(
  name='PostRewardToEvolverRequest',
  full_name='evolver.PostRewardToEvolverRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='evolver.PostRewardToEvolverRequest.reward', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=364,
)


_GETNNVARIABLESRESPONSE = _descriptor.Descriptor(
  name='GetNNVariablesResponse',
  full_name='evolver.GetNNVariablesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='evolver.GetNNVariablesResponse.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='variables', full_name='evolver.GetNNVariablesResponse.variables', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=438,
)

_GETNNVARIABLESRESPONSE.fields_by_name['variables'].message_type = ndarray__pb2._NDARRAY
DESCRIPTOR.message_types_by_name['RegisterLearnerRequest'] = _REGISTERLEARNERREQUEST
DESCRIPTOR.message_types_by_name['RegisterLearnerResponse'] = _REGISTERLEARNERRESPONSE
DESCRIPTOR.message_types_by_name['RegisterActorResponse'] = _REGISTERACTORRESPONSE
DESCRIPTOR.message_types_by_name['PostRewardToEvolverRequest'] = _POSTREWARDTOEVOLVERREQUEST
DESCRIPTOR.message_types_by_name['GetNNVariablesResponse'] = _GETNNVARIABLESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterLearnerRequest = _reflection.GeneratedProtocolMessageType('RegisterLearnerRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERLEARNERREQUEST,
  '__module__' : 'evolver_pb2'
  # @@protoc_insertion_point(class_scope:evolver.RegisterLearnerRequest)
  })
_sym_db.RegisterMessage(RegisterLearnerRequest)

RegisterLearnerResponse = _reflection.GeneratedProtocolMessageType('RegisterLearnerResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERLEARNERRESPONSE,
  '__module__' : 'evolver_pb2'
  # @@protoc_insertion_point(class_scope:evolver.RegisterLearnerResponse)
  })
_sym_db.RegisterMessage(RegisterLearnerResponse)

RegisterActorResponse = _reflection.GeneratedProtocolMessageType('RegisterActorResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERACTORRESPONSE,
  '__module__' : 'evolver_pb2'
  # @@protoc_insertion_point(class_scope:evolver.RegisterActorResponse)
  })
_sym_db.RegisterMessage(RegisterActorResponse)

PostRewardToEvolverRequest = _reflection.GeneratedProtocolMessageType('PostRewardToEvolverRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTREWARDTOEVOLVERREQUEST,
  '__module__' : 'evolver_pb2'
  # @@protoc_insertion_point(class_scope:evolver.PostRewardToEvolverRequest)
  })
_sym_db.RegisterMessage(PostRewardToEvolverRequest)

GetNNVariablesResponse = _reflection.GeneratedProtocolMessageType('GetNNVariablesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETNNVARIABLESRESPONSE,
  '__module__' : 'evolver_pb2'
  # @@protoc_insertion_point(class_scope:evolver.GetNNVariablesResponse)
  })
_sym_db.RegisterMessage(GetNNVariablesResponse)



_EVOLVERSERVICE = _descriptor.ServiceDescriptor(
  name='EvolverService',
  full_name='evolver.EvolverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=441,
  serialized_end=751,
  methods=[
  _descriptor.MethodDescriptor(
    name='Persistence',
    full_name='evolver.EvolverService.Persistence',
    index=0,
    containing_service=None,
    input_type=pingpong__pb2._PING,
    output_type=pingpong__pb2._PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterLearner',
    full_name='evolver.EvolverService.RegisterLearner',
    index=1,
    containing_service=None,
    input_type=_REGISTERLEARNERREQUEST,
    output_type=_REGISTERLEARNERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterActor',
    full_name='evolver.EvolverService.RegisterActor',
    index=2,
    containing_service=None,
    input_type=ndarray__pb2._EMPTY,
    output_type=_REGISTERACTORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostReward',
    full_name='evolver.EvolverService.PostReward',
    index=3,
    containing_service=None,
    input_type=_POSTREWARDTOEVOLVERREQUEST,
    output_type=ndarray__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNNVariables',
    full_name='evolver.EvolverService.GetNNVariables',
    index=4,
    containing_service=None,
    input_type=ndarray__pb2._EMPTY,
    output_type=_GETNNVARIABLESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVOLVERSERVICE)

DESCRIPTOR.services_by_name['EvolverService'] = _EVOLVERSERVICE

# @@protoc_insertion_point(module_scope)
