# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: learner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ndarray_pb2 as ndarray__pb2
import pingpong_pb2 as pingpong__pb2
import ma_variables_pb2 as ma__variables__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='learner.proto',
  package='learner',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rlearner.proto\x12\x07learner\x1a\rndarray.proto\x1a\x0epingpong.proto\x1a\x12ma_variables.proto\"\x90\x01\n\x15RegisterActorResponse\x12\x15\n\rmodel_abs_dir\x18\x01 \x01(\t\x12\x11\n\tunique_id\x18\x02 \x01(\x05\x12\x19\n\x11reset_config_json\x18\x03 \x01(\t\x12\x19\n\x11model_config_json\x18\x04 \x01(\t\x12\x17\n\x0fsac_config_json\x18\x05 \x01(\t\"\xb8\x02\n\nAddRequest\x12\x0f\n\x07ma_name\x18\x01 \x01(\t\x12\x1b\n\tl_indexes\x18\x02 \x01(\x0b\x32\x08.NDarray\x12!\n\x0fl_padding_masks\x18\x03 \x01(\x0b\x32\x08.NDarray\x12\x1e\n\x0cl_obses_list\x18\x04 \x03(\x0b\x32\x08.NDarray\x12\x1b\n\tl_actions\x18\x05 \x01(\x0b\x32\x08.NDarray\x12\x1b\n\tl_rewards\x18\x06 \x01(\x0b\x32\x08.NDarray\x12\x1f\n\rnext_obs_list\x18\x07 \x03(\x0b\x32\x08.NDarray\x12\x19\n\x07l_dones\x18\x08 \x01(\x0b\x32\x08.NDarray\x12\x1c\n\nl_mu_probs\x18\t \x01(\x0b\x32\x08.NDarray\x12%\n\x13l_seq_hidden_states\x18\n \x01(\x0b\x32\x08.NDarray\"(\n\x15GetNNVariablesRequest\x12\x0f\n\x07ma_name\x18\x01 \x01(\t2\xc3\x02\n\x0eLearnerService\x12\x1f\n\x0bPersistence\x12\x05.Ping\x1a\x05.Pong(\x01\x30\x01\x12\x37\n\rRegisterActor\x12\x06.Empty\x1a\x1e.learner.RegisterActorResponse\x12*\n\x12GetPolicyVariables\x12\x06.Empty\x1a\x0c.MAVariables\x12\"\n\x03\x41\x64\x64\x12\x13.learner.AddRequest\x1a\x06.Empty\x12<\n\x0eGetNNVariables\x12\x1e.learner.GetNNVariablesRequest\x1a\n.Variables\x12+\n\x13UpdateMANNVariables\x12\x0c.MAVariables\x1a\x06.Empty\x12\x1c\n\nForceClose\x12\x06.Empty\x1a\x06.Emptyb\x06proto3'
  ,
  dependencies=[ndarray__pb2.DESCRIPTOR,pingpong__pb2.DESCRIPTOR,ma__variables__pb2.DESCRIPTOR,])




_REGISTERACTORRESPONSE = _descriptor.Descriptor(
  name='RegisterActorResponse',
  full_name='learner.RegisterActorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_abs_dir', full_name='learner.RegisterActorResponse.model_abs_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='learner.RegisterActorResponse.unique_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reset_config_json', full_name='learner.RegisterActorResponse.reset_config_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_config_json', full_name='learner.RegisterActorResponse.model_config_json', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sac_config_json', full_name='learner.RegisterActorResponse.sac_config_json', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=222,
)


_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='learner.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ma_name', full_name='learner.AddRequest.ma_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_indexes', full_name='learner.AddRequest.l_indexes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_padding_masks', full_name='learner.AddRequest.l_padding_masks', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_obses_list', full_name='learner.AddRequest.l_obses_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_actions', full_name='learner.AddRequest.l_actions', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_rewards', full_name='learner.AddRequest.l_rewards', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_obs_list', full_name='learner.AddRequest.next_obs_list', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_dones', full_name='learner.AddRequest.l_dones', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_mu_probs', full_name='learner.AddRequest.l_mu_probs', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_seq_hidden_states', full_name='learner.AddRequest.l_seq_hidden_states', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=537,
)


_GETNNVARIABLESREQUEST = _descriptor.Descriptor(
  name='GetNNVariablesRequest',
  full_name='learner.GetNNVariablesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ma_name', full_name='learner.GetNNVariablesRequest.ma_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=579,
)

_ADDREQUEST.fields_by_name['l_indexes'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_padding_masks'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_obses_list'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_actions'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_rewards'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['next_obs_list'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_dones'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_mu_probs'].message_type = ndarray__pb2._NDARRAY
_ADDREQUEST.fields_by_name['l_seq_hidden_states'].message_type = ndarray__pb2._NDARRAY
DESCRIPTOR.message_types_by_name['RegisterActorResponse'] = _REGISTERACTORRESPONSE
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['GetNNVariablesRequest'] = _GETNNVARIABLESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterActorResponse = _reflection.GeneratedProtocolMessageType('RegisterActorResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERACTORRESPONSE,
  '__module__' : 'learner_pb2'
  # @@protoc_insertion_point(class_scope:learner.RegisterActorResponse)
  })
_sym_db.RegisterMessage(RegisterActorResponse)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'learner_pb2'
  # @@protoc_insertion_point(class_scope:learner.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

GetNNVariablesRequest = _reflection.GeneratedProtocolMessageType('GetNNVariablesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETNNVARIABLESREQUEST,
  '__module__' : 'learner_pb2'
  # @@protoc_insertion_point(class_scope:learner.GetNNVariablesRequest)
  })
_sym_db.RegisterMessage(GetNNVariablesRequest)



_LEARNERSERVICE = _descriptor.ServiceDescriptor(
  name='LearnerService',
  full_name='learner.LearnerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=582,
  serialized_end=905,
  methods=[
  _descriptor.MethodDescriptor(
    name='Persistence',
    full_name='learner.LearnerService.Persistence',
    index=0,
    containing_service=None,
    input_type=pingpong__pb2._PING,
    output_type=pingpong__pb2._PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterActor',
    full_name='learner.LearnerService.RegisterActor',
    index=1,
    containing_service=None,
    input_type=ndarray__pb2._EMPTY,
    output_type=_REGISTERACTORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPolicyVariables',
    full_name='learner.LearnerService.GetPolicyVariables',
    index=2,
    containing_service=None,
    input_type=ndarray__pb2._EMPTY,
    output_type=ma__variables__pb2._MAVARIABLES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='learner.LearnerService.Add',
    index=3,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=ndarray__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNNVariables',
    full_name='learner.LearnerService.GetNNVariables',
    index=4,
    containing_service=None,
    input_type=_GETNNVARIABLESREQUEST,
    output_type=ma__variables__pb2._VARIABLES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateMANNVariables',
    full_name='learner.LearnerService.UpdateMANNVariables',
    index=5,
    containing_service=None,
    input_type=ma__variables__pb2._MAVARIABLES,
    output_type=ndarray__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ForceClose',
    full_name='learner.LearnerService.ForceClose',
    index=6,
    containing_service=None,
    input_type=ndarray__pb2._EMPTY,
    output_type=ndarray__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEARNERSERVICE)

DESCRIPTOR.services_by_name['LearnerService'] = _LEARNERSERVICE

# @@protoc_insertion_point(module_scope)
