# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import learner_pb2 as learner__pb2
import ndarray_pb2 as ndarray__pb2
import pingpong_pb2 as pingpong__pb2


class LearnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Persistence = channel.stream_stream(
                '/learner.LearnerService/Persistence',
                request_serializer=pingpong__pb2.Ping.SerializeToString,
                response_deserializer=pingpong__pb2.Pong.FromString,
                )
        self.RegisterActor = channel.unary_unary(
                '/learner.LearnerService/RegisterActor',
                request_serializer=ndarray__pb2.Empty.SerializeToString,
                response_deserializer=learner__pb2.RegisterActorResponse.FromString,
                )
        self.GetAction = channel.unary_unary(
                '/learner.LearnerService/GetAction',
                request_serializer=learner__pb2.GetActionRequest.SerializeToString,
                response_deserializer=learner__pb2.Action.FromString,
                )
        self.GetPolicyVariables = channel.unary_unary(
                '/learner.LearnerService/GetPolicyVariables',
                request_serializer=ndarray__pb2.Empty.SerializeToString,
                response_deserializer=learner__pb2.NNVariables.FromString,
                )
        self.Add = channel.unary_unary(
                '/learner.LearnerService/Add',
                request_serializer=learner__pb2.AddRequest.SerializeToString,
                response_deserializer=ndarray__pb2.Empty.FromString,
                )
        self.GetNNVariables = channel.unary_unary(
                '/learner.LearnerService/GetNNVariables',
                request_serializer=ndarray__pb2.Empty.SerializeToString,
                response_deserializer=learner__pb2.NNVariables.FromString,
                )
        self.UpdateNNVariables = channel.unary_unary(
                '/learner.LearnerService/UpdateNNVariables',
                request_serializer=learner__pb2.NNVariables.SerializeToString,
                response_deserializer=ndarray__pb2.Empty.FromString,
                )
        self.ForceClose = channel.unary_unary(
                '/learner.LearnerService/ForceClose',
                request_serializer=ndarray__pb2.Empty.SerializeToString,
                response_deserializer=ndarray__pb2.Empty.FromString,
                )


class LearnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Persistence(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNNVariables(self, request, context):
        """Update variables from evolver
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNNVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Persistence': grpc.stream_stream_rpc_method_handler(
                    servicer.Persistence,
                    request_deserializer=pingpong__pb2.Ping.FromString,
                    response_serializer=pingpong__pb2.Pong.SerializeToString,
            ),
            'RegisterActor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterActor,
                    request_deserializer=ndarray__pb2.Empty.FromString,
                    response_serializer=learner__pb2.RegisterActorResponse.SerializeToString,
            ),
            'GetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAction,
                    request_deserializer=learner__pb2.GetActionRequest.FromString,
                    response_serializer=learner__pb2.Action.SerializeToString,
            ),
            'GetPolicyVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyVariables,
                    request_deserializer=ndarray__pb2.Empty.FromString,
                    response_serializer=learner__pb2.NNVariables.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=learner__pb2.AddRequest.FromString,
                    response_serializer=ndarray__pb2.Empty.SerializeToString,
            ),
            'GetNNVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNNVariables,
                    request_deserializer=ndarray__pb2.Empty.FromString,
                    response_serializer=learner__pb2.NNVariables.SerializeToString,
            ),
            'UpdateNNVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNNVariables,
                    request_deserializer=learner__pb2.NNVariables.FromString,
                    response_serializer=ndarray__pb2.Empty.SerializeToString,
            ),
            'ForceClose': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceClose,
                    request_deserializer=ndarray__pb2.Empty.FromString,
                    response_serializer=ndarray__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'learner.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LearnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Persistence(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/learner.LearnerService/Persistence',
            pingpong__pb2.Ping.SerializeToString,
            pingpong__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/RegisterActor',
            ndarray__pb2.Empty.SerializeToString,
            learner__pb2.RegisterActorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/GetAction',
            learner__pb2.GetActionRequest.SerializeToString,
            learner__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPolicyVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/GetPolicyVariables',
            ndarray__pb2.Empty.SerializeToString,
            learner__pb2.NNVariables.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/Add',
            learner__pb2.AddRequest.SerializeToString,
            ndarray__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNNVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/GetNNVariables',
            ndarray__pb2.Empty.SerializeToString,
            learner__pb2.NNVariables.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNNVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/UpdateNNVariables',
            learner__pb2.NNVariables.SerializeToString,
            ndarray__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ForceClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/ForceClose',
            ndarray__pb2.Empty.SerializeToString,
            ndarray__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
