# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_variables.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ndarray_pb2 as ndarray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ma_variables.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12ma_variables.proto\x1a\rndarray.proto\"(\n\tVariables\x12\x1b\n\tvariables\x18\x01 \x03(\x0b\x32\x08.NDarray\"\x95\x01\n\x0bMAVariables\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x33\n\x0cma_variables\x18\x02 \x03(\x0b\x32\x1d.MAVariables.MaVariablesEntry\x1a>\n\x10MaVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Variables:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[ndarray__pb2.DESCRIPTOR,])




_VARIABLES = _descriptor.Descriptor(
  name='Variables',
  full_name='Variables',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variables', full_name='Variables.variables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=77,
)


_MAVARIABLES_MAVARIABLESENTRY = _descriptor.Descriptor(
  name='MaVariablesEntry',
  full_name='MAVariables.MaVariablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MAVariables.MaVariablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MAVariables.MaVariablesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=229,
)

_MAVARIABLES = _descriptor.Descriptor(
  name='MAVariables',
  full_name='MAVariables',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='MAVariables.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ma_variables', full_name='MAVariables.ma_variables', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAVARIABLES_MAVARIABLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=229,
)

_VARIABLES.fields_by_name['variables'].message_type = ndarray__pb2._NDARRAY
_MAVARIABLES_MAVARIABLESENTRY.fields_by_name['value'].message_type = _VARIABLES
_MAVARIABLES_MAVARIABLESENTRY.containing_type = _MAVARIABLES
_MAVARIABLES.fields_by_name['ma_variables'].message_type = _MAVARIABLES_MAVARIABLESENTRY
DESCRIPTOR.message_types_by_name['Variables'] = _VARIABLES
DESCRIPTOR.message_types_by_name['MAVariables'] = _MAVARIABLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Variables = _reflection.GeneratedProtocolMessageType('Variables', (_message.Message,), {
  'DESCRIPTOR' : _VARIABLES,
  '__module__' : 'ma_variables_pb2'
  # @@protoc_insertion_point(class_scope:Variables)
  })
_sym_db.RegisterMessage(Variables)

MAVariables = _reflection.GeneratedProtocolMessageType('MAVariables', (_message.Message,), {

  'MaVariablesEntry' : _reflection.GeneratedProtocolMessageType('MaVariablesEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAVARIABLES_MAVARIABLESENTRY,
    '__module__' : 'ma_variables_pb2'
    # @@protoc_insertion_point(class_scope:MAVariables.MaVariablesEntry)
    })
  ,
  'DESCRIPTOR' : _MAVARIABLES,
  '__module__' : 'ma_variables_pb2'
  # @@protoc_insertion_point(class_scope:MAVariables)
  })
_sym_db.RegisterMessage(MAVariables)
_sym_db.RegisterMessage(MAVariables.MaVariablesEntry)


_MAVARIABLES_MAVARIABLESENTRY._options = None
# @@protoc_insertion_point(module_scope)
