# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_variables.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ndarray_pb2 as ndarray__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ma_variables.proto\x1a\rndarray.proto\";\n\tVariables\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x1b\n\tvariables\x18\x02 \x03(\x0b\x32\x08.NDarray\"\x82\x01\n\x0bMAVariables\x12\x33\n\x0cma_variables\x18\x01 \x03(\x0b\x32\x1d.MAVariables.MaVariablesEntry\x1a>\n\x10MaVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Variables:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_variables_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAVARIABLES_MAVARIABLESENTRY']._options = None
  _globals['_MAVARIABLES_MAVARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_VARIABLES']._serialized_start=37
  _globals['_VARIABLES']._serialized_end=96
  _globals['_MAVARIABLES']._serialized_start=99
  _globals['_MAVARIABLES']._serialized_end=229
  _globals['_MAVARIABLES_MAVARIABLESENTRY']._serialized_start=167
  _globals['_MAVARIABLES_MAVARIABLESENTRY']._serialized_end=229
# @@protoc_insertion_point(module_scope)
