# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ndarray_pb2 as ndarray__pb2
import pingpong_pb2 as pingpong__pb2
import replay_pb2 as replay__pb2


class ReplayServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Persistence = channel.stream_stream(
        '/ReplayService/Persistence',
        request_serializer=pingpong__pb2.Ping.SerializeToString,
        response_deserializer=pingpong__pb2.Pong.FromString,
        )
    self.Add = channel.unary_unary(
        '/ReplayService/Add',
        request_serializer=replay__pb2.AddRequest.SerializeToString,
        response_deserializer=ndarray__pb2.Empty.FromString,
        )
    self.Sample = channel.unary_unary(
        '/ReplayService/Sample',
        request_serializer=ndarray__pb2.Empty.SerializeToString,
        response_deserializer=replay__pb2.SampledData.FromString,
        )
    self.UpdateTDError = channel.unary_unary(
        '/ReplayService/UpdateTDError',
        request_serializer=replay__pb2.UpdateTDErrorRequest.SerializeToString,
        response_deserializer=ndarray__pb2.Empty.FromString,
        )
    self.UpdateTransitions = channel.unary_unary(
        '/ReplayService/UpdateTransitions',
        request_serializer=replay__pb2.UpdateTransitionsRequest.SerializeToString,
        response_deserializer=ndarray__pb2.Empty.FromString,
        )
    self.Clear = channel.unary_unary(
        '/ReplayService/Clear',
        request_serializer=ndarray__pb2.Empty.SerializeToString,
        response_deserializer=ndarray__pb2.Empty.FromString,
        )


class ReplayServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Persistence(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTDError(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTransitions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Clear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReplayServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Persistence': grpc.stream_stream_rpc_method_handler(
          servicer.Persistence,
          request_deserializer=pingpong__pb2.Ping.FromString,
          response_serializer=pingpong__pb2.Pong.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=replay__pb2.AddRequest.FromString,
          response_serializer=ndarray__pb2.Empty.SerializeToString,
      ),
      'Sample': grpc.unary_unary_rpc_method_handler(
          servicer.Sample,
          request_deserializer=ndarray__pb2.Empty.FromString,
          response_serializer=replay__pb2.SampledData.SerializeToString,
      ),
      'UpdateTDError': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTDError,
          request_deserializer=replay__pb2.UpdateTDErrorRequest.FromString,
          response_serializer=ndarray__pb2.Empty.SerializeToString,
      ),
      'UpdateTransitions': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTransitions,
          request_deserializer=replay__pb2.UpdateTransitionsRequest.FromString,
          response_serializer=ndarray__pb2.Empty.SerializeToString,
      ),
      'Clear': grpc.unary_unary_rpc_method_handler(
          servicer.Clear,
          request_deserializer=ndarray__pb2.Empty.FromString,
          response_serializer=ndarray__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ReplayService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
