build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-simple-roller\rl-test.exe
  linux: /data/zzy/linux-simple-roller/rl-test.x86_64

replay_host: 10.0.4.227
replay_port: 30555
learner_host: 10.0.4.227
learner_port: 30883
websocket_host: 10.0.4.227
websocket_port: 31396

reset_config:
  # copy: 1

update_policy_variables_per_step: 20
# add_trans_threshold: 100

# name: {time}
# sac: sac

batch_size: 1024
capacity: 1000000

sac_config:
  write_summary_graph: true
  # seed: 0
  # gamma: 0.99
  # tau: 0.005
  # save_model_per_step: 5000
  # write_summary_per_step: 20
  # update_target_per_step: 1
  # init_log_alpha: -4.6
  # use_auto_alpha: True
  # lr: 0.0003