default:
  base_config:
    env_type: GYM
    scene: Maze

    build_path: maze-random-5x5-v0

    max_step: -1
    max_iter: 1000
    n_agents: 10

  sac_config:
    burn_in_step: 5
    n_step: 3
    use_rnn: true
    use_prediction: true

nopre:
  base_config:
    name: 'nopre_{time}'
  sac_config:
    use_prediction: false