default:
  base_config:
    env_type: GYM
    scene: Maze

    build_path: maze-random-5x5-v0

    max_step: -1
    max_iter: 1000
    n_agents: 10
  replay_config: &visual_replay
    batch_size: 64
    capacity: 131072
  sac_config:
    seed: 42

    burn_in_step: 10
    n_step: 5
    use_rnn: true
    use_prediction: true