import importlib.util
import logging
import shutil
from pathlib import Path

import numpy as np

from .. import sac_main
from ..sac_main import Main
from ..utils import UnifiedElapsedTimer
from ..utils.enums import *
from .oc_agent import OC_MultiAgentsManager
from .option_selector_base import OptionSelectorBase


class OC_Main(Main):
    ma_manager: OC_MultiAgentsManager

    def __init__(self,
                 root_dir: Path | str,
                 config_dir: Path | str,
                 args):
        """
        root_dir: the root directory of asac
        config_path: the directory of config file
        args: command arguments generated by argparse
        """
        sac_main.MultiAgentsManager = OC_MultiAgentsManager

        self.root_dir = root_dir

        self._logger = logging.getLogger('oc')

        self._profiler = UnifiedElapsedTimer(self._logger)

        self._config_abs_dir = self._init_config(root_dir, config_dir, args)

        self._init_env()
        self._init_oc()

        self._run()

    def _init_oc(self):
        for n, mgr in self.ma_manager:
            # If nn models exists, load saved model, or copy a new one
            saved_nn_abs_dir = mgr.model_abs_dir / 'nn'
            if not self.force_env_nn and saved_nn_abs_dir.exists():
                nn_abs_path = saved_nn_abs_dir / f'{mgr.config["sac_config"]["nn"]}.py'
                spec = importlib.util.spec_from_file_location(f'{self._get_relative_package(nn_abs_path)}.{mgr.config["sac_config"]["nn"]}',
                                                              nn_abs_path)
                self._logger.info(f'Loaded nn from existed {nn_abs_path}')
            else:
                nn_abs_path = self._config_abs_dir / f'{mgr.config["sac_config"]["nn"]}.py'

                spec = importlib.util.spec_from_file_location(f'{self._get_relative_package(nn_abs_path)}.{mgr.config["sac_config"]["nn"]}',
                                                              nn_abs_path)
                self._logger.info(f'Loaded nn in env dir: {nn_abs_path}')
                if not self.force_env_nn:
                    shutil.copytree(self._config_abs_dir, saved_nn_abs_dir,
                                    ignore=lambda _, names: [name for name in names
                                                             if name == '__pycache__'])

            nn = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(nn)
            mgr.config['sac_config']['nn'] = nn

            mgr.set_rl(OptionSelectorBase(obs_names=mgr.obs_names,
                                          obs_shapes=mgr.obs_shapes,
                                          d_action_sizes=mgr.d_action_sizes,
                                          c_action_size=mgr.c_action_size,
                                          model_abs_dir=mgr.model_abs_dir,
                                          device=self.device,
                                          ma_name=None if len(self.ma_manager) == 1 else n,
                                          train_mode=self.train_mode and n not in self.inference_ma_names,
                                          last_ckpt=self.last_ckpt,

                                          nn_config=mgr.config['nn_config'],
                                          **mgr.config['sac_config'],

                                          **mgr.config['oc_config'],

                                          replay_config=mgr.config['replay_config']))

    def _extra_step(self,
                    ma_d_action: dict[str, np.ndarray],
                    ma_c_action: dict[str, np.ndarray]):
        if not self.train_mode:
            pass
            # ma_option = self.ma_manager.get_option()

            # # TODO: multiple agent options
            # ma_option = {n: int(option[0]) for n, option in ma_option.items()}
            # self.env.send_option(ma_option)
