default:
  base_config:
    env_type: GYM
    env_name: StackUniqueCorridor-v0
    env_args:
      map_width: 3
      target_type_num: 16
      target_type_dups: 1

    name: rnn_{time}

    n_envs: 100

  reset_config:
    stack_nesting: 0.5
    max_nesting_depth: 10
    key_target_num: 10
    block_gap: 5
    success_reward: 2.
    failure_reward: -1.
    max_episode_steps: 200

  sac_config:
    burn_in_step: 0
    n_step: 5
    seq_encoder: RNN

    discrete_dqn_like: true
    discrete_dqn_epsilon: 0.2
    use_priority: true # Whether using PER importance ratio

    batch_size: 1024

    learning_rate: 0.001

    ensemble_q_num: 5 # Number of Qs
    ensemble_q_sample: 3 # Number of min Qs

  oc_config:
    option_eplison: 0.1 # Probability of switching options
    option_seq_encoder: null
    terminal_entropy: 0. # Tending not to terminate >0, tending to terminate <0
    key_max_length: 200

offline:
  base_config:
    env_type: OFFLINE
    env_args:
      dataset_path: "C:/Users/fisher/Nextcloud/Documents/Python/MemoryCorridor/memory_corridor/dataset"
    name: offline_{time}
  sac_config:
    nn: nn_attn
    seq_encoder: ATTN

attn:
  base_config:
    name: attn_{time}
  sac_config:
    burn_in_step: 12
    nn: nn_attn
    seq_encoder: ATTN

oc_2:
  base_config:
    name: oc_2_rnn_{time}
  oc_config:
    num_options: 2

oc_3:
  base_config:
    name: oc_3_rnn_{time}
  oc_config:
    num_options: 3

oc_4:
  base_config:
    name: oc_4_rnn_{time}
  oc_config:
    num_options: 4

oc_2_dilated:
  inherited: oc_2
  base_config:
    name: oc_2_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_3_dilated:
  inherited: oc_3
  base_config:
    name: oc_3_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_4_dilated:
  inherited: oc_4
  base_config:
    name: oc_4_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_2_attn:
  inherited:
    - oc_2
    - attn
  base_config:
    name: oc_2_attn_{time}
  sac_config:
    nn: nn_oc_attn
    burn_in_step: 0

oc_3_attn:
  inherited:
    - oc_3
    - attn
  base_config:
    name: oc_3_attn_{time}
  sac_config:
    nn: nn_oc_attn
    burn_in_step: 0

oc_4_attn:
  inherited:
    - oc_4
    - attn
  base_config:
    name: oc_4_attn_{time}
  sac_config:
    nn: nn_oc_attn
    burn_in_step: 0

oc_2_attn_dilated:
  inherited: oc_2_attn
  base_config:
    name: oc_2_attn_dilated_{time}
  oc_config:
    use_dilation: true

oc_3_attn_dilated:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_{time}
  oc_config:
    use_dilation: true

oc_4_attn_dilated:
  inherited: oc_4_attn
  base_config:
    name: oc_4_attn_dilated_{time}
  oc_config:
    use_dilation: true

oc_3_attn_dilated_te04:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_te04_{time}
  oc_config:
    terminal_entropy: 0.04
    use_dilation: true

oc_3_attn_dilated_te03:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_te03_{time}
  oc_config:
    terminal_entropy: 0.03
    use_dilation: true

oc_3_attn_dilated_te02:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_te02_{time}
  oc_config:
    terminal_entropy: 0.02
    use_dilation: true

oc_3_attn_dilated_te01:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_te01_{time}
  oc_config:
    terminal_entropy: 0.01
    use_dilation: true

oc_3_attn_dilated_te00:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_te00_{time}
  oc_config:
    terminal_entropy: 0.0
    use_dilation: true

oc_3_attn_dilated_te-01:
  inherited: oc_3_attn
  base_config:
    name: oc_3_attn_dilated_te-01_{time}
  oc_config:
    terminal_entropy: -0.01
    use_dilation: true

oc_3_attn_dilated_te01_offline:
  inherited: oc_3_attn
  base_config:
    env_type: OFFLINE
    env_args:
      dataset_path: "C:/Users/fisher/Nextcloud/Documents/Python/MemoryCorridor/memory_corridor/dataset"
    name: oc_3_attn_dilated_te01_offline_{time}
  oc_config:
    terminal_entropy: 0.01
    use_dilation: true
