default:
  base_config:
    scene: VisualPyramid

    no_graphics: false

    build_path:
      win32: C:\Users\fisher\Nextcloud\Documents\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    name: "evolver_nopre_{time}"
    nn: nn_visual
    n_agents: 10
    reset_on_iteration: false

    attach_replay: true

    evolver_enabled: false

  net_config:
    evolver_host: visual-pyramid-nopre-ds-evolver

  reset_config:
    force_reset: true

  sac_config:
    burn_in_step: 30
    n_step: 3
    use_rnn: true

pre:
  base_config:
    name: "evolver_pre_{time}"
  net_config:
    evolver_host: visual-pyramid-pre-ds-evolver
  sac_config:
    use_prediction: true