base_config:
  build_path: 
    win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
    linux: /data/linux-RL-Envs/RL-Envs.x86_64
  scene: RayPyramid

  name: "ray10_nopre_{time}"
  max_iter: 500
  save_model_per_iter: 50
  reset_on_iteration: false
  
reset_config:
  force_reset: true
  avoid_wall: false

sac_config:
  seed: 42

  burn_in_step: 10
  n_step: 5
  use_rnn: true
  use_prediction: false

  _lambda: 0.99