default:
  base_config:
    env_type: MINIGRID
    env_name: MiniGrid-Empty-16x16-v0

    max_step: -1
    max_iter: 1000
    n_agents: 10

  sac_config:
    n_step: 3

    discrete_dqn_like: true

#    use_rnd: true
#    rnd_n_sample: 3