build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-simple-boat\RL-Envs.exe
  
# replay_host: 127.0.0.1
replay_port: 61001
# learner_host: 127.0.0.1
# learner_port: 61001
# websocket_host: 127.0.0.1
# websocket_port: 61002

reset_config:
  # copy: 1
  action: 0 # 0: can backward, 1: cannot backward
  reward: 1 # 0: include prior knowledge, 1: not included

# update_policy_variables_per_step: 100
# add_trans_threshold: 100
reset_on_iteration: false
# gamma: 0.99
# n_step: 1

# name: {time}
# sac: sac

replay_config:
  batch_size: 256
  # capacity: 1000000
  # alpha: 0.9

sac_config:
  write_summary_graph: true
  # seed: 0
  # tau: 0.005
  # save_model_per_step: 5000
  # write_summary_per_step: 20
  # update_target_per_step: 1
  # init_log_alpha: -4.6
  # use_auto_alpha: True
  # lr: 0.0003