build_path: 
  linux: /data/zzy/build-RL-Envs\RL-Envs.x86_64
scene: SimpleBoat
  
replay_host: 10.0.4.227
replay_port: 30168
learner_host: 10.0.4.227
learner_port: 30168
websocket_host: 10.0.4.227
websocket_port: 31322

reset_config:
  # copy: 1
  action: 0 # 0: can backward, 1: cannot backward
  reward: 1 # 0: include prior knowledge, 1: not included

# update_policy_variables_per_step: 100
# add_trans_threshold: 100
reset_on_iteration: false
# gamma: 0.99
n_step: 3

# name: {time}
# sac: sac

replay_config:
  batch_size: 256
  # capacity: 1000000
  # alpha: 0.9

sac_config:
  write_summary_graph: true
  # seed: 0
  # tau: 0.005
  # save_model_per_step: 5000
  # write_summary_per_step: 20
  # update_target_per_step: 1
  # init_log_alpha: -4.6
  # use_auto_alpha: True
  # lr: 0.0003