default:
  base_config:
    env_type: DM_CONTROL
    env_name: cartpole/swingup

    max_step: -1
    max_iter: 100
    n_envs: 10

  sac_config:
    seed: 42

    n_step: 10

    tau: 0.9
    v_lambda: 0.99
    init_log_alpha: 0
