default:
  base_config:
    env_type: GYM
    env_name: MemoryCorridor-v0

    name: rnn_{time}

    n_envs: 50

  reset_config:
    level_count: 1
    block_layer_count: 50
    block_gap: 10
    success_reward: 1.
    passage_reward: 0.05
    failure_reward: -0.1
    max_episode_steps: 1000

  sac_config:
    burn_in_step: 5
    n_step: 1
    seq_encoder: RNN

    discrete_dqn_like: true

    # use_rnd: true
    # rnd_n_sample: 50

  oc_config:
    option_eplison: 0.2  # Probability of switching options
    terminal_entropy: 0.0  # Tending not to terminate >0, tending to terminate <0

attn:
  base_config:
    name: attn_{time}
  sac_config:
    burn_in_step: 10
    n_step: 3

    nn: nn_attn
    seq_encoder: ATTN

oc_2:
  base_config:
    name: oc_2_rnn_{time}
  oc_config:
    num_options: 2

oc_3:
  base_config:
    name: oc_3_rnn_{time}
  oc_config:
    num_options: 3

oc_4:
  base_config:
    name: oc_4_rnn_{time}
  oc_config:
    num_options: 4

oc_2_dilated:
  inherited: oc_2
  base_config:
    name: oc_2_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_3_dilated:
  inherited: oc_3
  base_config:
    name: oc_3_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_4_dilated:
  inherited: oc_4
  base_config:
    name: oc_4_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_2_attn:
  inherited:
    - oc_2
    - attn
  base_config:
    name: oc_2_attn_{time}

oc_3_attn:
  inherited:
    - oc_3
    - attn
  base_config:
    name: oc_3_attn_{time}

oc_4_attn:
  inherited:
    - oc_4
    - attn
  base_config:
    name: oc_4_attn_{time}

oc_2_attn_dilated:
  inherited: oc_2_attn
  base_config:
    name: oc_2_dilated_attn_{time}
  oc_config:
    use_dilation: true

oc_3_attn_dilated:
  inherited: oc_3_attn
  base_config:
    name: oc_3_dilated_attn_{time}
  oc_config:
    use_dilation: true

oc_4_attn_dilated:
  inherited: oc_4_attn
  base_config:
    name: oc_4_dilated_attn_{time}
  oc_config:
    use_dilation: true
