base_config:
  build_path: 
    win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
    linux: /data/linux-RL-Envs/RL-Envs.x86_64
  scene: 3DBallHard

  sac: sac_hard
  max_iter: 200
  max_step: 500
  save_model_per_iter: 50
  
sac_config:
  seed: 42

  burn_in_step: 10
  n_step: 3
  use_rnn: true
  use_prediction: true

  init_log_alpha: -4.6
  _lambda: 0.99
  use_priority: true
  use_n_step_is: true
