base_config:
  build_path: 
    win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
    linux: /data/linux-RL-Envs/RL-Envs.x86_64
  scene: 3DBall

  max_step: 500
  # update_policy_variables_per_step: 50

net_config:
  replay_host: 58.199.162.110
  learner_host: 58.199.162.110

replay_config:
  capacity: 1000000

sac_config:
  seed: 42

  n_step: 3

  init_log_alpha: -4.6
  _lambda: 1
  use_auto_alpha: true
