default:
  base_config:
    env_type: GYM
    scene: MountainCar

    build_path: MountainCarContinuous-v0

    max_step: -1
    max_iter: 100
    save_model_per_iter: 50

  sac_config:
    seed: 42

    n_step: 10

    tau: 0.9
    _lambda: 0.99
    init_log_alpha: 0
    use_curiosity: true
    curiosity_strength: 500