default:
  base_config:
    env_type: GYM
    scene: Ant

    build_path: "AntBulletEnv-v0"

    max_iter: 3000
    n_agents: 10

  sac_config:
    write_summary_per_step: 100 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps
    save_model_per_minute: 5 # Save model every N minutes

    n_step: 5
    _lambda: 0.99

    use_normalization: true
    # use_curiosity: true
    # curiosity_strength: 0.3

hard:
  base_config: &hard_base
    scene: AntHard
    sac: sac_hard

  sac_config: &hard_sac
    burn_in_step: 30
    use_rnn: true
    use_prediction: true

hard_noextra:
  base_config:
    <<: *hard_base
    name: "noextra_{time}"

  sac_config:
    <<: *hard_sac
    use_extra_data: false

hard_nopre:
  base_config:
    <<: *hard_base
    name: "nopre_{time}"

  sac_config:
    <<: *hard_sac
    use_prediction: false
