default:
  base_config:
    env_type: GYM
    scene: Ant

    build_path: 'AntBulletEnv-v0'

    max_iter: 10000
    save_model_per_iter: 100
    n_agents: 10

  sac_config:
    seed: 42

    n_step: 3

    _lambda: 0.99