default:
  base_config:
    env_type: GYM
    scene: Ant

    build_path: 'AntBulletEnv-v0'

    max_iter: 3000
    n_agents: 10

  sac_config:
    use_auto_alpha: true

    n_step: 3
    _lambda: 0.99

    use_curiosity: true
    curiosity_strength: 0.2
    use_normalization: true

no_curiosity:
  sac_config:
    use_curiosity: false
    